### PR TITLE
Include passing of options.include through the queries.

### PR DESCRIPTION
**Pull request by jaalfaro**
I have need to pass through the includes option for queries.  Because of the way you build your options, this is not pass though by default.  I've added this capability.  

Hopefully you can accept my contribution  

Thank you for your great tool.

### CODE REVIEW

**Comment by rse** [comment]
As far as I know, the Sequelize include option lets you include related entities in the result. But can you be more specific why you want to use this instead of just including the relationships directly inside your GraphQL query and this way let the GraphQL engine follow the relationship? I mean, why `query { Foo(include: "bar") { quux } }` instead of `query { Foo { bar { ... } quux }`? Or do I miss something here?

**Comment by jaalfaro** [comment]
Ultimately, I'm using it to filter child tables.  Looking at the capabilities of sequelize, Primarily, I'm using it to filter results based on a child table.  I have 2 options on how I can go about it.  One is to add an required include with my filter criteria for the child table.  The second is to build a in query, but since I can't or at least have not figure out how to say where id in (select fk from table where ...)  This allows me to have the include with the criteria and sequelize build out the query for me.  I don't return any fields from the child table, they wouldn't show up anyway since there is no mapping.

**Comment by rse** [comment]
Ah, ok, I understand: you are not using "include" for eager loading of any results (as they would not show up anyway in the GraphQL query result if you not explicitly follow the relationship), but for a condition of the queried entity, based on some relationships of it. Makes sense to me. Although I've to confess, that in practice for such complex queries I just use a dedicated GraphQL resolver method instead of the CRUD operations provided by GraphQL-Tools-Sequelize.

One more question: you can just pass JSON, but the "include" field of Sequelize allows a lot more things, e.g. `include: [[sequelize.fn('COUNT', sequelize.col('hats')), 'no_hats']]` (from the Sequelize documentation). What about this? It has to be clear that this cannot be used in this form...

**Comment by jaalfaro** [comment]
I was thinking about that.  So, include has a specific structure.  So, What might be a good solution is to build a Ducky validation that checks the structure.  So my next question would be, can Ducky do recursive validations.  Since Include can have includes.  This might be the best solution.  I looked into it briefly, and figured out how to validate the first level, and I guess I could walk up the tree checking to see if there is a child Include.

**Comment by rse** [comment]
OK, I've now added an 'include' option for a condition on some requirements. Thanks for the idea.

**Pull request closed without merging**
